Generate a simple non-bootable firmware when not provided.
Arisotura/melonDS pull request #778
Opened 2020-10-03 21:04 UTC by Swordfish90

Hello guys,

I'd really like to help with the HLE bios task #367. It seems the drastic bios file linked in the issue are working very well, but sadly the games won't work without a proper firmware.

With this pull request, I'm trying to salvage some work done in #527, generating a dummy firmware when none are provided.

Using the free drastic bios files (linked in #367) I've been able to play every game I tried, so it sounds like a promising start.

Let me know if you want me to change anything.

2020-10-03 21:09 UTC, RSDuck commented
can you make the firmware configurable via a GUI dialog?

2020-10-03 21:23 UTC, Swordfish90 commented
@RSDuck What do you mean? Exposing settings like language and username?

2020-10-03 21:30 UTC, RSDuck commented
exactly

2020-10-03 23:12 UTC, Swordfish90 commented
@RSDuck Added the two options into settings. Let me know if I missed something.

2020-10-04 01:19 UTC, RSDuck commented on src/SPI.cpp
> +        Firmware[UserSettings + 0x06 + i * 2] = Config::FirmwareUserName[i];
this can't handle codepoints above first 256

2020-10-04 01:21 UTC, RSDuck commented on src/frontend/qt_sdl/EmuSettingsDialog.cpp
> +    form.addRow("Language", languagesBox);
could you add the remaining settings (birthday, message and favourite color) as well?

2020-10-04 01:22 UTC, RSDuck commented on src/SPI.cpp
> +    // setting up username
please make this optional if a firmware file is present

2020-10-04 01:23 UTC, RSDuck requested changes
needs a few additions, otherwise it's good!

2020-10-06 20:33 UTC, Swordfish90 commented
@RSDuck I just pushed the requested changes. Now the settings are applied only when loading the dummy firmware or when the user checks "Override firmware settings" which default to false.

2020-10-06 20:46 UTC, RSDuck commented
one last thing I should have asked earlier: can you implement the dialog via a QT xml file and structure it like the other dialogs? 

https://github.com/Arisotura/melonDS/blob/master/src/frontend/qt_sdl/main.cpp#L1775
https://github.com/Arisotura/melonDS/blob/master/src/frontend/qt_sdl/VideoSettingsDialog.h#L37

2020-10-06 21:02 UTC, Swordfish90 commented
No problem. I'll do that right away!

2020-10-06 21:55 UTC, kyandora commented
The username can overflow if it's larger than 10 characters (https://github.com/Swordfish90/melonDS/pull/3).
Although the strings are std::u16string katakana won't show up properly.

2020-10-06 22:36 UTC, Swordfish90 commented
@RSDuck Done. Feel free to let me know if something else is missing.

2020-10-06 22:36 UTC, RSDuck commented on src/frontend/qt_sdl/FirmwareSettingsDialog.h
> +    const QStringList colours {
that curly brace belongs to the next line

2020-10-06 22:40 UTC, RSDuck commented on src/frontend/qt_sdl/FirmwareSettingsDialog.h
> +    const QStringList languages {
same here

2020-10-06 22:54 UTC, kyandora commented
Would configuration pollution be an issue? I've got a patch for the strings, but mangling it config.cpp compliant requires 36 integers.

2020-10-06 22:58 UTC, RSDuck commented
can you elaborate?

2020-10-06 23:11 UTC, kyandora commented
FirmwareUsername and FirmwareMessage are stored as unsigned shorts. During configuration QT parses and saves the strings in UTF-16. The result can be memcopied into the firmware.
As melonDS stores it's settings in chars and integers, the arrays would need to be split into single shorts (`{"FirmwareMessage00", 0, &FirmwareMessage[0], 68, NULL, 0},`).

2020-10-06 23:25 UTC, RSDuck commented
I see, though I think it's preferable to save the strings as UTF-8 because it fits better with the rest of the code and to keep the configs editable by hand

2020-10-07 20:13 UTC, RSDuck commented
@Swordfish90 and @kyandora can we merge this?

2020-10-07 20:49 UTC, Swordfish90 commented
@RSDuck I think so. Yesterday I applied the changes to the curly braces (my religion is different :smile:), so if you like the dialog layout we're good to go.

2020-10-08 21:24 UTC, kyandora commented
Thanks to our previously unused iconv dependency, the strings are now proper UTF-16LE. https://github.com/Swordfish90/melonDS/pull/4

2020-12-27 16:12 UTC, YoshiRulz commented
Something like this would significantly reduce the work required to make an EmuHawk integration MVP.

2020-12-29 14:47 UTC, fancythedeveloper commented
MVP?

2020-12-29 15:38 UTC, YoshiRulz commented
Minimum viable product. We just need roms, firmware, video, input, and savestates.

2021-02-21 19:14 UTC, rafaelvcaetano commented
I don't know if there are still plans to merge this or not, but I've been working on a similar implementation for the standalone Android version and whenever a ROM requires wireless communications, it just hangs. This causes some games to be unplayable, like the Gen 4 Pokémon games because they perform some wireless related operations in the main menu screen, making it impossible to enter the game. I've gotten around it by modifying some values in the firmware's Wifi Calibration/Settings section. Local multiplayer seems to retain its functionality but online connectivity seems be broken when configuring an access point. Haven't tested these changes in the PC version yet.

2021-06-05 00:30 UTC, RSDuck commented
sorry for lettings this wait for so long, but I think the UTF8 -> UTF16 conversion is still done incorrectly. I suggest using https://en.cppreference.com/w/cpp/locale/codecvt_utf8_utf16 for it (eventhough it's deprecated, but there's no good replacement in the std library currently, so might as well use it).

2021-10-02 10:18 UTC, vadosnaprimer commented
Did https://github.com/Arisotura/melonDS/pull/1174 resolve this PR?

2021-10-02 10:19 UTC, RayyanAnsari commented
no the updated version of this PR is https://github.com/Arisotura/melonDS/pull/1175

2022-03-09 16:40 UTC, Arisotura commented
well this seems to be no longer needed

2022-03-09 16:40 UTC, closed without merging